version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - configs/.env

  mongo:
    image: mongo
    restart: always
    env_file:
      - configs/.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - configs/.env
