---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16.2'
      - name: build
        run: make install build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: '--disable unused -v'

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.0.0
        with:
          file_or_dir: 'configs'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16.2'
      - name: install godog
        run: go get github.com/cucumber/godog/cmd/godog@v0.11.0
      - uses: actions/checkout@v2
      - name: test
        run: make install test
